FROM python:3.10-slim

# Install system deps for OpenCV + glib + FFMPEG
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Create working directory
WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Install Python deps
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

    # Download YOLO model
RUN apt-get update && apt-get install -y wget
RUN wget https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11m.pt -O /app/yolo11m.pt


# Copy backend code
COPY . .

# Expose port
EXPOSE 8000

# Start server
# at the end of your Dockerfile, replace the current CMD with:
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"]
